# Site settings
title: Into The Woods 2016
email: hi@aigaintothewoods.com/
description: > # this means to ignore newlines until "baseurl:"
  Designing between the lines means looking past
  what’s in front of you and finding power in the
  nexpected. Into the Woods 2016 celebrates provocative
  ideas, integrative thinking, and boundary-defying design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.aigaintothewoods.com/" # the base hostname & protocol for your site
twitter_username: aigaseattle
github_username:  aigaseattle

# Build settings
markdown: kramdown

# Collections
collections:
  - workshops
  - speakers